# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: /
    weight: 10
  - name: Experience
    url: experience/
    weight: 11
  - name: Projects
    url: projects/
    weight: 12
  - name: Highlights
    url: highlights/
    weight: 13
  - name: Interests
    url: interests/
    weight: 14
  - name: Chords
    url: chords/
    weight: 15
  - name: blog
    url: blog/
    weight: 21
  - name: events
    url: events/
    weight: 22
  - name: courses
    url: courses/
    weight: 23
  - name: publications
    url: publications/
    weight: 24
